/** Generate a stable-format optimistic temporary id. */
export declare const generateTempId: (prefix?: string) => string;
/** Return true when an id was generated by `generateTempId`. */
export declare const isTempId: (id: string | null | undefined) => boolean;
/** Create a monotonic numeric sequence for optimistic ordering. */
export declare const createOptimisticSequence: () => {
    next: () => number;
};
//# sourceMappingURL=generateTempId.d.ts.map