/**
 * Generate a stable-format optimistic temporary id: `temp[-prefix]-<timestamp>-<counter>`. Ids generated
 * within the same millisecond share the timestamp but get a strictly increasing counter, so ids stay
 * unique and sortable even under rapid-fire calls.
 *
 * @param prefix Optional label folded into the id (e.g. a model name) for readability in logs/storage.
 * @returns A new temp id, always prefixed with `temp-` (or `temp-<prefix>-`), recognized by `isTempId`.
 */
export declare const generateTempId: (prefix?: string) => string;
/**
 * Return true when an id was generated by `generateTempId` (starts with `temp-`).
 *
 * @param id Candidate id; non-string and nullish values return `false`.
 */
export declare const isTempId: (id: string | null | undefined) => boolean;
//# sourceMappingURL=generateTempId.d.ts.map
