import { act } from 'react-test-renderer'
import { bootDb, configureDb, defineModel, f, flushPersistence, resetRuntime } from '../../index'
import { createAcceptanceTransport, createMemoryPlane, renderCounted, setupAcceptanceRuntime } from './harness'

const document = { kind: `Document`, definitions: [] } as never

describe(`A15 maintenance and poller`, () => {
  // @ts-expect-error maintenance scope fields must exist on the stored model row
  defineModel({ id: `A15MaintenanceType`, name: `MaintenanceType`, fields: { bucket: f.str() }, maintenance: { maxRowsPerScope: [{ scopeField: `missing`, limit: 1, compare: () => 0 }] } })
  it(`replay orphan sweep subsumes temporary row cleanup during boot`, async () => {
    const storage = createMemoryPlane(); const transport = createAcceptanceTransport(); setupAcceptanceRuntime({ storage, transport })
    const model = defineModel({ id: `A15Stale`, name: `Stale`, fields: { createdAt: f.num() }, gc: `exempt` })
    model.insertStoredMany([{ id: `temp-old-1`, createdAt: Date.now() - 2000 }, { id: `temp-fresh-1`, createdAt: Date.now() }, { id: `normal`, createdAt: Date.now() }])
    flushPersistence(); await bootDb({ storage, transport }); expect(model.get(`temp-old-1`)).toBeUndefined(); expect(model.get(`temp-fresh-1`)).toBeUndefined(); expect(model.get(`normal`)).toBeDefined()
  })
  it(`trims scoped rows while evaluating cross-model protection at boot`, async () => {
    const storage = createMemoryPlane(); const transport = createAcceptanceTransport(); setupAcceptanceRuntime({ storage, transport }); const locks = defineModel({ id: `A15Locks`, name: `Locks`, fields: { rowId: f.str() }, gc: `exempt` }); locks.insertStored({ id: `lock`, rowId: `old` }); const model = defineModel({ id: `A15Trim`, name: `Trim`, fields: { bucket: f.str(), rank: f.num() }, gc: `exempt`, maintenance: { maxRowsPerScope: [{ scopeField: `bucket`, limit: 1, compare: (left, right) => right.rank - left.rank, protect: () => row => locks.getWhere({ rowId: row.id }).length > 0 }] } }); model.insertStoredMany([{ id: `new`, bucket: `b`, rank: 3 }, { id: `middle`, bucket: `b`, rank: 2 }, { id: `old`, bucket: `b`, rank: 1 }]); flushPersistence(); const result = await bootDb({ storage, transport }); expect(model.get(`new`)).toBeDefined(); expect(model.get(`old`)).toBeDefined(); expect(model.get(`middle`)).toBeUndefined(); expect(result.maintenance).toContainEqual({ model: `A15Trim`, task: `maxRowsPerScope`, affected: 1 })
  })
  it(`replaces maintenance runners when a model is redefined`, async () => { const storage = createMemoryPlane(); const transport = createAcceptanceTransport(); setupAcceptanceRuntime({ storage, transport }); defineModel({ id: `A15Replace`, name: `Replace`, fields: { bucket: f.str(), rank: f.num() }, gc: `exempt`, maintenance: { maxRowsPerScope: [{ scopeField: `bucket`, limit: 0, compare: (left, right) => right.rank - left.rank }] } }); const second = defineModel({ id: `A15Replace`, name: `Replace`, fields: { bucket: f.str(), rank: f.num() }, gc: `exempt`, maintenance: { maxRowsPerScope: [{ scopeField: `bucket`, limit: 2, compare: (left, right) => right.rank - left.rank }] } }); second.insertStoredMany([{ id: `one`, bucket: `b`, rank: 2 }, { id: `two`, bucket: `b`, rank: 1 }]); flushPersistence(); const result = await bootDb({ storage, transport }); expect(second.get(`one`)).toBeDefined(); expect(second.get(`two`)).toBeDefined(); expect(result.maintenance.filter(report => report.model === `A15Replace`)).toHaveLength(1) })
  it(`keeps maintenance deletions durable across a later boot`, async () => { const storage = createMemoryPlane(); const transport = createAcceptanceTransport(); setupAcceptanceRuntime({ storage, transport }); const model = defineModel({ id: `A15Reactive`, name: `Reactive`, fields: { bucket: f.str(), rank: f.num() }, gc: `exempt`, maintenance: { maxRowsPerScope: [{ scopeField: `bucket`, limit: 1, compare: (left, right) => right.rank - left.rank }] } }); model.insertStoredMany([{ id: `old`, bucket: `b`, rank: 1 }, { id: `kept`, bucket: `b`, rank: 2 }]); flushPersistence(); await bootDb({ storage, transport }); const reader = renderCounted(() => model.use.where({}).rows()); expect(reader.result().map(row => row.id)).toEqual([`kept`]); reader.unmount(); flushPersistence(); await bootDb({ storage, transport }); expect(model.get(`old`)).toBeUndefined(); expect(model.get(`kept`)).toBeDefined() })
  it(`polls, applies terminal data, and stops the model poller`, async () => { jest.useFakeTimers(); const transport = createAcceptanceTransport({ query: async <TData,>() => ({ data: { title: `done`, terminal: true } as TData }) }); setupAcceptanceRuntime({ transport }); const model = defineModel({ id: `A15Poller`, name: `Poller`, fields: { title: f.str() } }); model.insertStored({ id: `row`, title: `pending` }); const stop = jest.fn(); const poller = model.poller(`status`, { document, apply: (id, data: { title: string; terminal: boolean }) => model.patch(id, { title: data.title }), isTerminal: (data: { title: string; terminal: boolean }) => data.terminal, intervalMs: 10, maxAttempts: 3, onSessionStop: stop }); const reader = renderCounted(() => model.use.row(`row`)); const detach = poller.attach(`row`); await act(async () => { await Promise.resolve() }); expect(reader.result()?.title).toBe(`done`); expect(poller.isPolling(`row`)).toBe(false); expect(stop).toHaveBeenCalledWith(`row`, `terminal`); detach(); reader.unmount(); jest.useRealTimers() })
  it(`fences a resolving poller request after runtime reset`, async () => { let resolve!: (value: { data: { title: string; terminal: boolean } }) => void; const transport = createAcceptanceTransport({ query: <TData,>() => new Promise<{ data: TData }>(done => { resolve = done as never }) }); setupAcceptanceRuntime({ transport }); const model = defineModel({ id: `A15PollerReset`, name: `PollerReset`, fields: { title: f.str() } }); model.insertStored({ id: `row`, title: `old` }); const poller = model.poller(`status`, { document, apply: (id, data: { title: string }) => model.patch(id, { title: data.title }), isTerminal: () => false, intervalMs: 10, maxAttempts: 3 }); poller.attach(`row`); act(() => { resetRuntime(); model.insertStored({ id: `row`, title: `fresh` }) }); await act(async () => { resolve({ data: { title: `stale`, terminal: false } }); await Promise.resolve() }); expect(model.get(`row`)?.title).toBe(`fresh`) })
  it(`stops polling after the last model poller consumer detaches`, async () => { jest.useFakeTimers(); const transport = createAcceptanceTransport({ query: async <TData,>() => ({ data: { terminal: false } as TData }) }); setupAcceptanceRuntime({ transport }); const model = defineModel({ id: `A15PollerDetach`, name: `PollerDetach`, fields: { title: f.str() } }); const poller = model.poller(`status`, { document, apply: () => {}, isTerminal: (data: { terminal: boolean }) => data.terminal, intervalMs: 10, maxAttempts: 10 }); const detach = poller.attach(`row`); await act(async () => { await Promise.resolve() }); detach(); const calls = transport.calls.length; act(() => { jest.advanceTimersByTime(100) }); expect(transport.calls).toHaveLength(calls); jest.useRealTimers() })
  it(`logs model poller fetch failures with its model-qualified identity`, async () => { const errors: unknown[][] = []; const storage = createMemoryPlane(); const transport = createAcceptanceTransport({ query: async () => Promise.reject(new Error(`failed`)) }); configureDb({ storage, transport, logger: { debug: () => {}, error: (...args) => errors.push(args) } }); const model = defineModel({ id: `A15PollerLog`, name: `PollerLog`, fields: { title: f.str() } }); const poller = model.poller(`status`, { document, apply: () => {}, isTerminal: () => false, intervalMs: 10, maxAttempts: 1 }); poller.attach(`row`); await act(async () => { await Promise.resolve() }); expect(errors.some(args => JSON.stringify(args).includes(`A15PollerLog:status`))).toBe(true) })
})
