"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.isTempId = exports.generateTempId = exports.createOptimisticSequence = void 0;
let counter = 0;
let lastTimestamp = 0;

/** Generate a stable-format optimistic temporary id. */
const generateTempId = prefix => {
  const now = Date.now();
  if (now === lastTimestamp) {
    counter++;
  } else {
    counter = 0;
    lastTimestamp = now;
  }
  const base = prefix ? `temp-${prefix}` : 'temp';
  return `${base}-${now}-${counter}`;
};

/** Return true when an id was generated by `generateTempId`. */
exports.generateTempId = generateTempId;
const isTempId = id => typeof id === 'string' && id.startsWith('temp-');

/** Create a monotonic numeric sequence for optimistic ordering. */
exports.isTempId = isTempId;
const createOptimisticSequence = () => {
  let value = 0;
  return {
    next: () => value++
  };
};
exports.createOptimisticSequence = createOptimisticSequence;
//# sourceMappingURL=generateTempId.js.map