"use strict";

let counter = 0;
let lastTimestamp = 0;

/**
 * Generate a stable-format optimistic temporary id: `temp[-prefix]-<timestamp>-<counter>`. Ids generated
 * within the same millisecond share the timestamp but get a strictly increasing counter, so ids stay
 * unique and sortable even under rapid-fire calls.
 *
 * @param prefix Optional label folded into the id (e.g. a model name) for readability in logs/storage.
 * @returns A new temp id, always prefixed with `temp-` (or `temp-<prefix>-`), recognized by `isTempId`.
 */
export const generateTempId = prefix => {
  const now = Date.now();
  if (now === lastTimestamp) {
    counter++;
  } else {
    counter = 0;
    lastTimestamp = now;
  }
  const base = prefix ? `temp-${prefix}` : 'temp';
  return `${base}-${now}-${counter}`;
};

/**
 * Return true when an id was generated by `generateTempId` (starts with `temp-`).
 *
 * @param id Candidate id; non-string and nullish values return `false`.
 * @returns `true` when the id matches the temp id pattern.
 */
export const isTempId = id => typeof id === 'string' && id.startsWith('temp-');
//# sourceMappingURL=generateTempId.js.map