export { configureDb, flushPersistence } from './dsl/configure';
export { getDbTransport, setDbTransport } from './core/transport';
export type { DbDefaults, DbRetryClass, DbRetryPolicy } from './dsl/configure';
export { bootDb, suspendDb } from './dsl/lifecycle';
export type { BootDbOptions } from './dsl/lifecycle';
export { DbProvider } from './dsl/DbProvider';
export type { DbProviderProps } from './dsl/DbProvider';
export type { MaintenanceReport } from './dsl/maintenanceRegistry';
export { resetRuntime, registerReset } from './core/reset';
export { mmkvStoragePlane } from './core/planes/storagePlane';
export type { StoragePlane } from './core/planes/storagePlane';
export { defineModel } from './dsl/defineModel';
export type { ScopeHandle } from './dsl/defineModel';
export type { ViewConfig, ViewIncludeModel, ViewIncludeSpec } from './dsl/defineView';
export { scope } from './dsl/scope';
export type { ScopeSpec, ScopeCoverage } from './dsl/scope';
export { collectGarbage } from './core/gc';
export type { GcReport } from './core/gc';
export { belongsTo, hasMany, hasOne, references } from './core/relations';
export { f } from './schema/f';
export { defineShape, projectShape, readShape, readShapeOrThrow } from './schema/shape';
export type { QueryResult, ExtractSink } from './dsl/defineQuery';
export { defineFetch } from './dsl/defineFetch';
export type { FetchResult } from './dsl/defineFetch';
export type { MutateCallbacks, ScopePlacement } from './dsl/defineMutation';
export type { LiveQueryHandle } from './dsl/defineModel';
export { defineCommand } from './dsl/defineCommand';
export type { IngestDecl } from './dsl/defineIngest';
export { createDbSubscriptionEffects, createDbSubscriptionRuntime, defineDbSubscriptionEntry } from './core/subscriptionRuntime';
export type { LoadingState, DbTransport, DbWhere } from './types';
export type { ModelInput, ModelStored } from './schema/infer';
export type { InferShapeStored } from './schema/infer';
export { generateTempId, isTempId } from './utils/generateTempId';
export { isIncomingNewer } from './core/invariants';
export { stringifyNullish } from './utils/normalizeHelpers';
export { pickDefined, pickPresent } from './utils/pickDefined';
export { mergeOptimisticSnapshot } from './mutations/base/mergeOptimisticSnapshot';
export { mergeOptimisticMedia } from './utils/optimisticMedia';
export { createThrottledSingleFlight, createKeyedArrayPatcher, createIdArrayPatcher, createNestedObjectPatcher, createSingletonStatics } from './utils/runtimePrimitives';
export { reconcileOptimisticRows } from './utils/runtimePrimitives';
export { patchWhenRowExists, waitForRow } from './core/rowWaiters';
//# sourceMappingURL=index.d.ts.map