export { configureDb } from './dsl/configure';
export type { DbDefaults } from './dsl/configure';
export { resetRuntime, registerReset } from './core/reset';
export { mmkvStoragePlane } from './core/planes/storagePlane';
export type { StoragePlane } from './core/planes/storagePlane';
export { defineModel } from './dsl/defineModel';
export type { ScopeHandle } from './dsl/defineModel';
export { scope } from './dsl/scope';
export type { ScopeSpec, Coverage } from './dsl/scope';
export { belongsTo, hasMany, hasOne } from './core/relations';
export { compositeId } from './schema/schema';
export { f } from './schema/f';
export { defineShape, projectShape, readFieldsPatch, readShape, readShapeOrThrow } from './schema/shape';
export { defineQuery } from './dsl/defineQuery';
export type { QueryResult, ExtractSink } from './dsl/defineQuery';
export { defineMutation } from './dsl/defineMutation';
export { defineIngest } from './dsl/defineIngest';
export type { IngestDecl } from './dsl/defineIngest';
export { createDbSubscriptionEffects, createDbSubscriptionRuntime, defineDbSubscriptionEntry } from './core/subscriptionRuntime';
export { useStableItems as useStableProjection, useStableEntity, useStableSorted, useJoinedEntities, useOrderedEntities, pickEqual } from './queries/base/shared';
export { EMPTY_IDS, createUniqueIds } from './queries/base/uniqueIds';
export { computeLoadingState } from './queries/base/loadingState';
export type { LoadingState, DbTransport, DbWhere } from './types';
export type { ModelInput, ModelStored } from './schema/infer';
export { generateTempId, isTempId } from './utils/generateTempId';
export { castNode, castNodes } from './utils/typeBoundary';
export { toStr } from './utils/normalizeHelpers';
export { pickDefined, pickPresent } from './utils/pickDefined';
export { mergeOptimisticSnapshot } from './mutations/base/mergeOptimisticSnapshot';
export { mergeOptimisticMedia } from './utils/optimisticMedia';
export { createModelStatusPoller } from './utils/modelStatusPoller';
export { createThrottledSingleFlight, createKeyedBatchBuffer, createKeyedArrayPatcher, createNestedObjectPatcher, singletonStatics } from './utils/runtimePrimitives';
export { patchWhenPresent, waitForRow } from './core/rowWaiters';
//# sourceMappingURL=index.d.ts.map