let counter = 0;
let lastTimestamp = 0;

/** Generate a stable-format optimistic temporary id. */
export const generateTempId = (prefix?: string): string => {
  const now = Date.now();
  if (now === lastTimestamp) {
    counter++;
  } else {
    counter = 0;
    lastTimestamp = now;
  }
  const base = prefix ? `temp-${prefix}` : 'temp';
  return `${base}-${now}-${counter}`;
};

/** Return true when an id was generated by `generateTempId`. */
export const isTempId = (id: string | null | undefined): boolean => typeof id === 'string' && id.startsWith('temp-');

/** Create a monotonic numeric sequence for optimistic ordering. */
export const createOptimisticSequence = (): { next: () => number } => {
  let value = 0;
  return {
    next: () => value++
  };
};
